version: '3.3'

services:
  mariadb:
    restart: always
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    env_file: .env
    networks:
      - app-network
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    restart: always
    build: ./requirements/wordpress/
    container_name: wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - app-network
    volumes:
      - www-volume:/var/www/html

  nginx:
    restart: always
    build: ./requirements/nginx
    container_name: nginx
    hostname: localhost
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - www-volume:/var/www/html

  redis:
    restart: always
    build: requirements/bonus/redis/
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - wordpress
    networks:
      - app-network
    env_file: .env

  adminer:
    restart: always
    build: requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    ports:
      - 9000:8080
    depends_on:
      - nginx
    networks:
      - app-network
    env_file: .env

  ftps:
    restart: always
    build: requirements/bonus/ftps/
    image: ftps
    container_name: ftps
    ports:
      - "21:21"
      - "21000:21000"
    networks:
      - app-network
    env_file: .env
    volumes:
      - www-volume:/var/www/html

  portainer:
    restart: always
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    env_file: .env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    security_opt:
      - no-new-privileges:true

networks:
  app-network:
    driver: bridge

volumes:
  db-volume:
    driver_opts:
      type: none
      device: /home/achanel/data/db
      o: bind
  www-volume:
    driver_opts:
      type: none
      device: /home/achanel/data/www
      o: bind