version: "3"
services:

  mariadb:
    restart: always
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    restart: always
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - www-volume:/var/www/html/wordpress

  nginx:
    restart: always
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - www-volume:/var/html/wordpress

  networks:
    inception:
      driver: bridge

  volumes:
    db-volume:
      driver_opts:
        type: none
        device: /home/achanel/data/db
        o: bind
    www-volume:
      driver_opts:
        type: none
        device: /home/achanel/data/www
        o: bind